/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;

import Controllers.CustomerController;
import Controllers.SQL;
import Models.Customers;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ❤Kevin Felix Caluag❤
 */
public class Checkin extends javax.swing.JPanel {

    /**
     * Creates new form Checkin
     */
    public Checkin() {
        initComponents();
        checkindate.setText(getDateNow());
        checkintime.setText(getTimeNow());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkindate = new javax.swing.JLabel();
        cusFname1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cusMname1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cusLname1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cusAddress1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        checkintime = new javax.swing.JTextField();
        save1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rooms1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cusContact2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("CHECK IN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 54));

        checkindate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(checkindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 210, 41));
        jPanel2.add(cusFname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 72, 213, 41));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 13)); // NOI18N
        jLabel10.setText("Middle name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 73, 41));
        jPanel2.add(cusMname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 220, 41));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel11.setText("Last name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 73, 41));
        jPanel2.add(cusLname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 213, 41));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setText("CHECK IN DATE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 41));
        jPanel2.add(cusAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 220, 41));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setText("Contact #");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 80, 41));
        jPanel2.add(checkintime, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 220, 41));

        save1.setText("SAVE");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel2.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 126, 61));

        delete1.setText("DELETE");
        jPanel2.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 126, 61));

        jLabel14.setText("ROOMS");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 73, 36));

        jPanel2.add(rooms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 210, 40));

        jLabel1.setText("CHECK IN TIME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 90, 40));
        jPanel2.add(cusContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 120, 220, 41));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel15.setText("First name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 72, 73, 41));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel16.setText("Address");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 41));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    public CustomerController custo = new CustomerController();
    
     public  SQL sql = new SQL();
     
     public Customers customers;
     
     public String getDateNow(){
         Date date = Calendar.getInstance().getTime();  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");  
        String strDate = dateFormat.format(date);
        return strDate;
     }
     
     public String getTimeNow(){
         Date date = Calendar.getInstance().getTime();  
        DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss");  
        String strTime = timeFormat.format(date);
        return strTime;
     }
    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed

    }//GEN-LAST:event_save1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkindate;
    private javax.swing.JTextField checkintime;
    private javax.swing.JTextField cusAddress1;
    private javax.swing.JTextField cusContact2;
    private javax.swing.JTextField cusFname1;
    private javax.swing.JTextField cusLname1;
    private javax.swing.JTextField cusMname1;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> rooms1;
    private javax.swing.JButton save1;
    // End of variables declaration//GEN-END:variables
}
