/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;

import Controllers.CheckinAndOutController;
import Controllers.CustomerController;
import Controllers.RoomController;
import Controllers.SQL;
import Models.Customers;
import Models.CheckinAndOut;
import Views.Dashboards.ContainerManipulator;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sweetalerts.Alerts;

/**
 *
 * @author ❤Kevin Felix Caluag❤
 */
public class CheckinPanels extends javax.swing.JPanel {

    /**
     * Creates new form CheckinPanels
     */
    
        public JPanel lalag;
        public RoomController roomControll = new RoomController();   
        public CustomerController custo = new CustomerController();
        public Customers customers;
        public CheckinAndOutController check_in_out_controll = new CheckinAndOutController();
        public int id;
    
    public CheckinPanels(JPanel lalag) throws SQLException {
        initComponents();
        roomControll.showRooms(rooms1);
        roomControll.ShowRoomInCheckin(jtbl_roomsTable);
        checkindate.setText(check_in_out_controll.getDateNow());
        checkintime1.setText(check_in_out_controll.getTimeNow());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkindate = new javax.swing.JLabel();
        jtxt_cusFname1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxt_cusMname1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxt_cusLname1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxt_cusAddress1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rooms1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtxt_cusContact2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        checkintime1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_roomsTable = new javax.swing.JTable();
        jbtn_checkin = new javax.swing.JButton();
        jtxt_cussearch = new javax.swing.JTextField();
        jcbo_hoursrange = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 77, 77));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(128, 179, 255));
        jPanel2.setForeground(new java.awt.Color(64, 63, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 63, 64));
        jLabel2.setText("CHECK IN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 54));

        checkindate.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jPanel2.add(checkindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 210, 40));

        jtxt_cusFname1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jtxt_cusFname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cusFname1KeyTyped(evt);
            }
        });
        jPanel2.add(jtxt_cusFname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 213, 30));

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel10.setText("M.I");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 60, 41));

        jtxt_cusMname1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jtxt_cusMname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cusMname1KeyTyped(evt);
            }
        });
        jPanel2.add(jtxt_cusMname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 220, 30));

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel11.setText("LAST NAME");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 110, 41));

        jtxt_cusLname1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jtxt_cusLname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cusLname1KeyTyped(evt);
            }
        });
        jPanel2.add(jtxt_cusLname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 213, 30));

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel12.setText("CHECK IN DATE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, 30));

        jtxt_cusAddress1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jtxt_cusAddress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cusAddress1KeyTyped(evt);
            }
        });
        jPanel2.add(jtxt_cusAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 210, 30));

        jLabel13.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel13.setText("CONTACT #");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 100, 40));

        jLabel14.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel14.setText("ROOMS");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 73, 36));

        rooms1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(rooms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 210, 30));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel1.setText("CHECK IN TIME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 130, 40));

        jtxt_cusContact2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jtxt_cusContact2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cusContact2KeyTyped(evt);
            }
        });
        jPanel2.add(jtxt_cusContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 220, 30));

        jLabel15.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel15.setText("FIRST NAME");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 41));

        jLabel16.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel16.setText("ADDRESS");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 80, 41));

        checkintime1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jPanel2.add(checkintime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 190, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 1120, 380));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOTEL MANAGEMENT");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 590, 50));

        jtbl_roomsTable.setBackground(new java.awt.Color(153, 153, 153));
        jtbl_roomsTable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jtbl_roomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RoomType", "BedType", "Rate", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_roomsTable.setOpaque(false);
        jtbl_roomsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_roomsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_roomsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 1120, 220));

        jbtn_checkin.setBackground(new java.awt.Color(51, 102, 255));
        jbtn_checkin.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_checkin.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_checkin.setText("CHECK-IN");
        jbtn_checkin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, null, null));
        jbtn_checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_checkinActionPerformed(evt);
            }
        });
        add(jbtn_checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, 50));

        jtxt_cussearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cussearchActionPerformed(evt);
            }
        });
        jtxt_cussearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_cussearchKeyPressed(evt);
            }
        });
        add(jtxt_cussearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, 30));

        jcbo_hoursrange.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jcbo_hoursrange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 Hours\t", "6 Hours", "12 Hours", "24 Hours", " " }));
        add(jcbo_hoursrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jtbl_roomsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_roomsTableMouseClicked
        id = (int) jtbl_roomsTable.getValueAt(jtbl_roomsTable.getSelectedRow(),0);
        int kev = JOptionPane.showConfirmDialog(null,"Room ID : " + id);
        if (kev==0) {
            rooms1.setSelectedItem(String.valueOf(id));
        }
    }//GEN-LAST:event_jtbl_roomsTableMouseClicked

    private void jtxt_cusFname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cusFname1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= 'A') && (c <= 'Z') || (c >= 'a') && (c <= 'z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_cusFname1KeyTyped

    private void jtxt_cusMname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cusMname1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
       if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'Z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_cusMname1KeyTyped

    private void jtxt_cusLname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cusLname1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'Z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_cusLname1KeyTyped

    private void jtxt_cusAddress1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cusAddress1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
         if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'Z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_cusAddress1KeyTyped

    private void jtxt_cusContact2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cusContact2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_cusContact2KeyTyped

    private void jtxt_cussearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cussearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cussearchActionPerformed

     public  SQL sql = new SQL();
     public Connection con = sql.getConnection();
     
    
    
    private void jtxt_cussearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cussearchKeyPressed
        DefaultTableModel model = (DefaultTableModel)jtbl_roomsTable.getModel();
//        model.setRowCount(0);
        TableRowSorter<DefaultTableModel>tr = new TableRowSorter<DefaultTableModel>(model);
        jtbl_roomsTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jtxt_cussearch.getText().trim()));
           
    }//GEN-LAST:event_jtxt_cussearchKeyPressed

    private void jbtn_checkinActionPerformed(java.awt.event.ActionEvent evt) {                                      
        
        if (checkInputs()==true) {
             new Alerts("error").setVisible(true);  
         }else{
        customers = new Customers(1,jtxt_cusFname1.getText(),jtxt_cusMname1.getText(),jtxt_cusLname1.getText(),jtxt_cusAddress1.getText(),jtxt_cusContact2.getText());   
        try {
            custo.createCustomer(customers);
            boolean check =  check_in_out_controll.checkIn(jtbl_roomsTable,checkindate, checkintime1, rooms1);
            if (check==true) {
                jtxt_cusFname1.setText("");
               jtxt_cusMname1.setText("");
               jtxt_cusLname1.setText("");
               jtxt_cusAddress1.setText("");
               jtxt_cusContact2.setText("");
               rooms1.removeAllItems();
               roomControll.showRooms(rooms1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CheckinPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }    
    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
      
    } 
       
     private boolean checkInputs(){
        String notice = "Theres Have A Field That Empty Please make an Input";
        if (jtxt_cusFname1.getText().isEmpty()||jtxt_cusMname1.getText().isEmpty()||jtxt_cusLname1.getText().isEmpty()||jtxt_cusAddress1.getText().isEmpty()||jtxt_cusContact2.getText().isEmpty()){
//            new Alerts("fillfield").setVisible(true);
                return true;
        }
            return false;
        
      }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkindate;
    private javax.swing.JLabel checkintime1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_checkin;
    private javax.swing.JComboBox<String> jcbo_hoursrange;
    private javax.swing.JTable jtbl_roomsTable;
    private javax.swing.JTextField jtxt_cusAddress1;
    private javax.swing.JTextField jtxt_cusContact2;
    private javax.swing.JTextField jtxt_cusFname1;
    private javax.swing.JTextField jtxt_cusLname1;
    private javax.swing.JTextField jtxt_cusMname1;
    private javax.swing.JTextField jtxt_cussearch;
    private javax.swing.JComboBox<String> rooms1;
    // End of variables declaration//GEN-END:variables
}
