/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;

import Controllers.CheckinAndOutController;
import Controllers.CustomerController;
import Controllers.RoomController;
import Controllers.SQL;
import Models.Customers;
import Models.CheckinAndOut;
import Views.Dashboards.ContainerManipulator;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import sweetalerts.Alerts;

/**
 *
 * @author ❤Kevin Felix Caluag❤
 */
public class CheckinPanels extends javax.swing.JPanel {

    /**
     * Creates new form CheckinPanels
     */
    
        public JPanel lalag;
        public RoomController roomControll = new RoomController();   
        public CustomerController custo = new CustomerController();
        public Customers customers;
        public CheckinAndOutController check_in_out_controll = new CheckinAndOutController();
        public int id;
    
    public CheckinPanels(JPanel lalag) throws SQLException {
        initComponents();
        roomControll.showRooms(rooms1);
        roomControll.ShowRoomInCheckin(roomsTable);
        checkindate.setText(check_in_out_controll.getDateNow());
        checkintime1.setText(check_in_out_controll.getTimeNow());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkindate = new javax.swing.JLabel();
        cusFname1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cusMname1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cusLname1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cusAddress1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rooms1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cusContact2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        checkintime1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomsTable = new javax.swing.JTable();
        save1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 77, 77));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(128, 179, 255));
        jPanel2.setForeground(new java.awt.Color(64, 63, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 63, 64));
        jLabel2.setText("CHECK IN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 54));

        checkindate.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel2.add(checkindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 210, 41));

        cusFname1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cusFname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusFname1KeyTyped(evt);
            }
        });
        jPanel2.add(cusFname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 213, 30));

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel10.setText("M.I");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 60, 41));

        cusMname1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cusMname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusMname1KeyTyped(evt);
            }
        });
        jPanel2.add(cusMname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 220, 30));

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel11.setText("LAST NAME");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 110, 41));

        cusLname1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cusLname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusLname1KeyTyped(evt);
            }
        });
        jPanel2.add(cusLname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 213, 30));

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel12.setText("CHECK IN DATE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, 41));

        cusAddress1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cusAddress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusAddress1KeyTyped(evt);
            }
        });
        jPanel2.add(cusAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 210, 30));

        jLabel13.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel13.setText("CONTACT #");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 100, 40));

        jLabel14.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel14.setText("ROOMS");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 73, 36));

        rooms1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(rooms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 210, 30));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel1.setText("CHECK IN TIME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 130, 40));

        cusContact2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cusContact2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusContact2KeyTyped(evt);
            }
        });
        jPanel2.add(cusContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 220, 30));

        jLabel15.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel15.setText("FIRST NAME");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 41));

        jLabel16.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel16.setText("ADDRESS");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 80, 41));

        checkintime1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(checkintime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 190, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 1120, 380));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOTEL MANAGEMENT");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 610, 50));

        roomsTable.setBackground(new java.awt.Color(153, 153, 153));
        roomsTable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        roomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RoomType", "BedType", "Rate", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roomsTable.setOpaque(false);
        roomsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roomsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 1120, 220));

        save1.setBackground(new java.awt.Color(51, 102, 255));
        save1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        save1.setText("CHECK-IN");
        save1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, null, null));
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 126, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void roomsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsTableMouseClicked
        id = (int) roomsTable.getValueAt(roomsTable.getSelectedRow(),0);
        int kev = JOptionPane.showConfirmDialog(null,"Room ID : " + id);
        if (kev==0) {
            rooms1.setSelectedItem(String.valueOf(id));
        }
    }//GEN-LAST:event_roomsTableMouseClicked

    private void cusFname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusFname1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= 'A') && (c <= 'Z') || (c >= 'a') && (c <= 'z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_cusFname1KeyTyped

    private void cusMname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusMname1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= 'A') && (c <= 'Z') || (c >= 'a') && (c <= 'z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_cusMname1KeyTyped

    private void cusLname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusLname1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= 'A') && (c <= 'Z') || (c >= 'a') && (c <= 'z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_cusLname1KeyTyped

    private void cusAddress1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusAddress1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= 'A') && (c <= 'Z') || (c >= 'a') && (c <= 'z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_cusAddress1KeyTyped

    private void cusContact2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusContact2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_cusContact2KeyTyped

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        
        if (checkInputs()==true) {
             new Alerts("error").setVisible(true);  
         }else{
        customers = new Customers(1,cusFname1.getText(),cusMname1.getText(),cusLname1.getText(),cusAddress1.getText(),cusContact2.getText());   
        try {
            custo.createCustomer(customers);
            boolean check =  check_in_out_controll.checkIn(roomsTable,checkindate, checkintime1, rooms1);
            if (check==true) {
                cusFname1.setText("");
               cusMname1.setText("");
               cusLname1.setText("");
               cusAddress1.setText("");
               cusContact2.setText("");
               rooms1.removeAllItems();
               roomControll.showRooms(rooms1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CheckinPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }    
    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
      
    } 
       
     private boolean checkInputs(){
        String notice = "Theres Have A Field That Empty Please make an Input";
        if (cusFname1.getText().isEmpty()||cusMname1.getText().isEmpty()||cusLname1.getText().isEmpty()||cusAddress1.getText().isEmpty()||cusContact2.getText().isEmpty()){
//            new Alerts("fillfield").setVisible(true);
                return true;
        }
            return false;
        
      }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkindate;
    private javax.swing.JLabel checkintime1;
    private javax.swing.JTextField cusAddress1;
    private javax.swing.JTextField cusContact2;
    private javax.swing.JTextField cusFname1;
    private javax.swing.JTextField cusLname1;
    private javax.swing.JTextField cusMname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> rooms1;
    private javax.swing.JTable roomsTable;
    private javax.swing.JButton save1;
    // End of variables declaration//GEN-END:variables
}
