/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;

import java.awt.Color;
import java.awt.Component;
import javax.swing.ComboBoxEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;

/**
 *
 * @author ❤Kevin Felix Caluag❤
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public String kevin =  "KEVIN FELIX CALUAG";
    
    public NewJFrame() {
        initComponents();
        jComboBox1.setEditable(true);
        ComboBoxEditor editor = jComboBox1.getEditor();
        if (editor != null) {
        Component editorComp = editor.getEditorComponent();
        if (editorComp instanceof JComponent) {
        JComponent editorJComp = (JComponent) editorComp;
        editorJComp.setForeground(Color.red);
//        jComboBox1.setEditable(false);
        }
        }
//        jComboBox1.setModel(pop());
//        jComboBox1.setRenderer(new ImageTextRenderer());
//        jComboBox1.setBackground(new Color(25,20,255));
//        JOptionPane.showMessageDialog(this,jComboBox1.getSelectedIndex());
    }
    
    private DefaultComboBoxModel pop(){
        DefaultComboBoxModel kev = new DefaultComboBoxModel();
        kev.addElement(new ImagesNText(new ImageIcon("src\\Images\\kevin.jpg"),kevin));
        kev.addElement(new ImagesNText(new ImageIcon("src\\Images\\logout.png"),"LOG OUT"));
        kev.addElement(new ImagesNText(new ImageIcon("src\\Images\\logout.png"),"LOG OUT"));
        return kev;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(83, 140, 198));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "asdasd", "asdasd", "asda", "sd", "asd", "sdfads" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 11, 242, 52));

        jPanel1.setBackground(new java.awt.Color(83, 140, 198));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 140, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
//        DefaultComboBoxModel model = (DefaultComboBoxModel)jComboBox1.getModel();
//        int vin = model.getSize();
//        for (int i = 0; i < vin; i++) {
//            if (i==jComboBox1.getSelectedIndex()) {
//                String name = ((ImagesNText)jComboBox1.getSelectedItem()).getname();
//                JOptionPane.showMessageDialog(this,name);
//            }
//        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    public class ImageTextRenderer extends JLabel implements ListCellRenderer{

        @Override
        public Component getListCellRendererComponent(JList list, Object val, int index, boolean selected, boolean focused) {
           ImagesNText it  = (ImagesNText) val;
           setIcon(it.getImg());
           setText(it.getname());
           
            if (selected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            }else{
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            }
           setFont(list.getFont());
           
           return this;
           
        }
        
    }
    public class ImagesNText {

        private Icon img;
        private String name;
        
        public ImagesNText(Icon img,String name) {
            this.img=img;
            this.name=name;
        }
        
        public Icon getImg(){
            return img;
        }
        
        public void setImg(Icon img){
            this.img=img;
        }
        
        public String getname(){
            return name;
        }
        
        public void setName(String name){
            this.name=name;
        }
    }
}
