/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;

import Controllers.Authentication;
import Controllers.SQL;
import Models.Users;
import Views.Authentication.Login;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.management.relation.Role;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sweetalerts.Alerts;

/**
 *
 * @author CALUAG FAMILY
 */
public class ProfileSettings extends javax.swing.JFrame {

    /**
     * Creates new form ProfileSettings
     */
    static int UserIdSended;
    Users userModel;
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
     Webcam wc;
     
    public ProfileSettings(int user_id,JFrame out) throws SQLException {
        initComponents();
        this.out=out;
        this.UserIdSended=user_id;
        userId.setText(String.valueOf(UserIdSended));
        getUserInfo();
        wc = Webcam.getDefault();
        wc.setViewSize(WebcamResolution.VGA.getSize());
//        jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userActionPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_uaname2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtxt_umi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jtxt_usn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jtxt_uadd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jtxt_ucon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jtxt_uname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        udob = new com.toedter.calendar.JDateChooser();
        upass = new javax.swing.JPasswordField();
        jbtn_Update = new javax.swing.JButton();
        jbtn_viewpass = new javax.swing.JButton();
        jbtn_hidepass = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jbtn_addpic = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        userId = new javax.swing.JLabel();
        userProfile = new jroundborder.JLabelRound();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userActionPanel2.setBackground(new java.awt.Color(0, 204, 204));
        userActionPanel2.setPreferredSize(new java.awt.Dimension(306, 642));
        userActionPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FNAME :");
        userActionPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 240, 70, 30));

        jtxt_uaname2.setBackground(new java.awt.Color(0, 204, 204));
        jtxt_uaname2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_uaname2.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_uaname2.setBorder(null);
        jtxt_uaname2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_uaname2KeyTyped(evt);
            }
        });
        userActionPanel2.add(jtxt_uaname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 270, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 270, 10));

        jtxt_umi.setBackground(new java.awt.Color(0, 204, 204));
        jtxt_umi.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_umi.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_umi.setBorder(null);
        jtxt_umi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_umiActionPerformed(evt);
            }
        });
        userActionPanel2.add(jtxt_umi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 282, 270, 30));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MN:");
        userActionPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 290, 50, 20));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 270, 5));

        jtxt_usn.setBackground(new java.awt.Color(0, 204, 204));
        jtxt_usn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_usn.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_usn.setBorder(null);
        userActionPanel2.add(jtxt_usn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 322, 270, 30));

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SN :");
        userActionPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 330, 50, 20));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 270, 5));

        jtxt_uadd.setBackground(new java.awt.Color(0, 204, 204));
        jtxt_uadd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_uadd.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_uadd.setBorder(null);
        userActionPanel2.add(jtxt_uadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 362, 270, 30));

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADD :");
        userActionPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 60, 30));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 270, 5));

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DOB :");
        userActionPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 61, 30));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 270, 5));

        jtxt_ucon.setBackground(new java.awt.Color(0, 204, 204));
        jtxt_ucon.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_ucon.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_ucon.setBorder(null);
        jtxt_ucon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_uconKeyTyped(evt);
            }
        });
        userActionPanel2.add(jtxt_ucon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 442, 270, 30));

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CON.# :");
        userActionPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 61, 30));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 270, -1));

        jtxt_uname.setBackground(new java.awt.Color(0, 204, 204));
        jtxt_uname.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_uname.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_uname.setBorder(null);
        jtxt_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_unameActionPerformed(evt);
            }
        });
        userActionPanel2.add(jtxt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 270, 30));

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("UNAME:");
        userActionPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 490, 70, 30));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 250, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PASS :");
        userActionPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 61, 30));

        udob.setBackground(new java.awt.Color(0, 204, 204));
        udob.setDateFormatString("yyyy-MM-dd");
        udob.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        udob.setOpaque(false);
        userActionPanel2.add(udob, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 270, 30));

        upass.setBackground(new java.awt.Color(0, 204, 204));
        upass.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        upass.setForeground(new java.awt.Color(255, 255, 255));
        upass.setBorder(null);
        userActionPanel2.add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 250, 30));

        jbtn_Update.setBackground(new java.awt.Color(0, 102, 255));
        jbtn_Update.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_Update.setText("UPDATE");
        jbtn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_UpdateActionPerformed(evt);
            }
        });
        userActionPanel2.add(jbtn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 600, 250, 36));

        jbtn_viewpass.setBackground(new java.awt.Color(0, 204, 255));
        jbtn_viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eyes.png"))); // NOI18N
        jbtn_viewpass.setBorderPainted(false);
        jbtn_viewpass.setContentAreaFilled(false);
        jbtn_viewpass.setFocusPainted(false);
        jbtn_viewpass.setFocusable(false);
        jbtn_viewpass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_viewpass.setMaximumSize(new java.awt.Dimension(55, 49));
        jbtn_viewpass.setMinimumSize(new java.awt.Dimension(55, 49));
        jbtn_viewpass.setPreferredSize(new java.awt.Dimension(60, 49));
        jbtn_viewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_viewpassActionPerformed(evt);
            }
        });
        userActionPanel2.add(jbtn_viewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 30, 30));

        jbtn_hidepass.setBackground(new java.awt.Color(0, 204, 255));
        jbtn_hidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hide.png"))); // NOI18N
        jbtn_hidepass.setBorderPainted(false);
        jbtn_hidepass.setContentAreaFilled(false);
        jbtn_hidepass.setFocusPainted(false);
        jbtn_hidepass.setFocusable(false);
        jbtn_hidepass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_hidepass.setPreferredSize(new java.awt.Dimension(60, 49));
        jbtn_hidepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_hidepassActionPerformed(evt);
            }
        });
        userActionPanel2.add(jbtn_hidepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 30, 30));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        userActionPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 270, 10));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        userActionPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 650));

        jbtn_addpic.setBackground(new java.awt.Color(0, 204, 204));
        jbtn_addpic.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jbtn_addpic.setText("+");
        jbtn_addpic.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jbtn_addpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_addpicActionPerformed(evt);
            }
        });
        userActionPanel2.add(jbtn_addpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 40, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        userActionPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 43, 36));

        jLabel13.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Profile");
        userActionPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 50));

        userId.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        userActionPanel2.add(userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, 40));
        userActionPanel2.add(userProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 250, 150));

        jButton3.setText("++");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        userActionPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 50, 30));

        getContentPane().add(userActionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jbtn_addpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_addpicActionPerformed
           Camera vin =  new Camera(jtxt_uaname2.getText());
           JOptionPane.showMessageDialog(this, vin);

//                new VideoFeeder().start();
//                jButton3.setVisible(true);
    }//GEN-LAST:event_jbtn_addpicActionPerformed

    private void jbtn_hidepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_hidepassActionPerformed
        jbtn_viewpass.setVisible(true);
        jbtn_hidepass.setVisible(false);
        upass.setEchoChar('*');
    }//GEN-LAST:event_jbtn_hidepassActionPerformed

    private void jbtn_viewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_viewpassActionPerformed
        upass.setEchoChar((char)0);
        jbtn_hidepass.setVisible(true);
        jbtn_viewpass.setVisible(false);
    }//GEN-LAST:event_jbtn_viewpassActionPerformed

    public  SQL sql = new SQL();
    public Connection con = sql.getConnection();
    int role_id;
    Authentication auth = new Authentication();
    String userprofiles;
    Image kevs;
    ImageIcon kevss;
    
    private void getUserInfo() throws SQLException{
        String tanong = "SELECT * FROM `users` WHERE user_id='"+UserIdSended+"';";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(tanong);

            while(rs.next()){
                role_id=rs.getInt("role_id");
                userprofiles=rs.getString("profile");
                jtxt_uaname2.setText(rs.getString("user_Fname"));
                jtxt_umi.setText(rs.getString("user_Mname"));
                jtxt_usn.setText(rs.getString("user_Lname"));
                jtxt_uadd.setText(rs.getString("user_address"));
                udob.setDate(rs.getDate("user_DOB"));
                jtxt_ucon.setText(rs.getString("user_contactnum"));
                jtxt_uname.setText(rs.getString("user_username"));
                upass.setText(auth.decrypt(rs.getString("user_password")));
            }
             if (userprofiles==null) {
                  ImageIcon vin = new ImageIcon(getClass().getResource("/Images/Pictures/sampleuser.jpg"));
                  kevs = vin.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
                  kevss = new ImageIcon(kevs);
             }else{
                ImageIcon vin = new ImageIcon(getClass().getResource("/Images/Pictures/"+userprofiles+".jpg"));
                kevs = vin.getImage().getScaledInstance(300, 150, Image.SCALE_SMOOTH);
                kevss = new ImageIcon(kevs);
             }
             userProfile.setIcon(kevss);
    }
    
    static JFrame out;
    
    public void signOut(JFrame out){
        this.out=out;
        int k = JOptionPane.showConfirmDialog(this,"You need To Logout To Take Effect your Profile Update");
        if (k==0){
            out.dispose();
            this.dispose();
            new Login().setVisible(true);
        }
    }
    
    public boolean updateUser(Users users) throws SQLException{
        String updates = "UPDATE users SET profile = ?, user_Fname = ?,user_Mname = ?,user_Lname = ?,user_address = ?,user_DOB = ?,user_contactnum = ?,user_username = ?,user_password = ? WHERE user_id = '" + UserIdSended + "'";
        PreparedStatement st = con.prepareStatement(updates);
        st.setString(1, users.getuser_Fname());
        st.setString(2, users.getuser_Fname());
        st.setString(3, users.getuser_Mname());
        st.setString(4, users.getuser_Lname());
        st.setString(5, users.getuser_address());
        st.setString(6, users.getuser_DOB());
        st.setString(7, users.getuser_contactnum());
        st.setString(8, users.getuser_username());
        st.setString(9, auth.encrypt(users.getuser_password()));
        
        int i = st.executeUpdate();
        if (i > 0) {
            new Alerts("update").setVisible(true);
//            this.dispose();
            signOut(out);
            return true;
        }else{
            return false;
        }
     }
    
    private void jbtn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_UpdateActionPerformed
            userModel=new Users(0,role_id,userProfile.getText(),jtxt_uaname2.getText(), jtxt_umi.getText(),jtxt_usn.getText(),jtxt_uadd.getText(),df.format(udob.getDate()),jtxt_ucon.getText(),jtxt_uname.getText(),String.valueOf(upass.getPassword()));
        try {
            updateUser(userModel);
        } catch (SQLException ex) {
            Logger.getLogger(ProfileSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtn_UpdateActionPerformed

    private void jtxt_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_unameActionPerformed

    private void jtxt_uconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_uconKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_PERIOD) ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jtxt_uconKeyTyped

    private void jtxt_uaname2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_uaname2KeyTyped
        char c = evt.getKeyChar();
        if (!((c >= 'A') && (c <= 'Z') || (c >= 'a') && (c <= 'z') ||
            (c == KeyEvent.VK_PERIOD) ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jtxt_uaname2KeyTyped

    private void jtxt_umiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_umiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_umiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
             ImageIO.write(wc.getImage(), "JPG", new File("src/Images/Pictures/" + jtxt_uaname2.getText() + ".jpg"));
            wc.close();
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ProfileSettings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ProfileSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    Image img;
    
    class VideoFeeder extends Thread {
    
          public void run(){
          
               while(true){
                   img = wc.getImage();
                   userProfile.setIcon(new ImageIcon(img));
//                       Thread.sleep(5000);
                }
          
          }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProfileSettings(UserIdSended,out).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ProfileSettings.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbtn_Update;
    private javax.swing.JButton jbtn_addpic;
    private javax.swing.JButton jbtn_hidepass;
    private javax.swing.JButton jbtn_viewpass;
    private javax.swing.JTextField jtxt_uadd;
    public javax.swing.JTextField jtxt_uaname2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jtxt_ucon;
    private javax.swing.JTextField jtxt_umi;
    private javax.swing.JTextField jtxt_uname;
    private javax.swing.JTextField jtxt_usn;
    private com.toedter.calendar.JDateChooser udob;
    private javax.swing.JPasswordField upass;
    private javax.swing.JPanel userActionPanel2;
    public javax.swing.JLabel userId;
    private jroundborder.JLabelRound userProfile;
    // End of variables declaration//GEN-END:variables
}
