/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;


import Controllers.BedsController;
import Controllers.RatesController;
import Controllers.RoomTypesController;
import Controllers.SQL;
import Models.Roomtypes;
import Models.Rates;
import Models.Beds;
import Views.Dashboards.ContainerManipulator;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chelsea
 */
public class Rate_RT_BedPanels extends javax.swing.JPanel {

        public  SQL sql = new SQL();
        public JPanel lalagyanan;
         public int index,index1,id;
         RoomTypesController roomtypeControll = new RoomTypesController(lalagyanan); 
         ArrayList<Roomtypes> roomtypelist = roomtypeControll.roomtypeList();
         RatesController ratesControll = new RatesController(lalagyanan); 
         ArrayList<Rates> ratelist = ratesControll.rateList();
         BedsController bedsControll = new BedsController(lalagyanan); 
         ArrayList<Beds> bedlist = bedsControll.bedList();
         
    /**
     * Creates new form Rate_RT_BedPanels
     */
    public Rate_RT_BedPanels(JPanel lalagyanan) throws SQLException {
        initComponents();
        this.lalagyanan=lalagyanan;
        roomtypeControll = new RoomTypesController(lalagyanan);
        ratesControll=new RatesController(lalagyanan);
        bedsControll=new BedsController(lalagyanan);
        roomtypeControll.showRoomtypes(jtbl_RTtable);
        ratesControll.showRates(jtbl_ratestable);
       bedsControll.showBeds(jtble_bedtable);
          
            if (roomtypelist.size()==0) {
                jtxt_RTid.setText("1");
          
            }else{
                index1 = roomtypelist.size()-1;
                index = roomtypelist.get(index1).getRT_id() + 1;        
                jtxt_RTid.setText(String.valueOf(index));

            }
//    }

         if (ratelist.size()==0) {
            jtxt_RateID.setText("1");
          
        }else{
            index1 = ratelist.size()-1;
            index = ratelist.get(index1).getrate_id() + 1;        
            jtxt_RateID.setText(String.valueOf(index));
    
        }
          if (bedlist.size()==0) {
            jtxt_BedID.setText("1");
          
        }else{
            index1 = bedlist.size()-1;
            index = bedlist.get(index1).getbed_id() + 1;        
            jtxt_BedID.setText(String.valueOf(index));
          }
          tagokamuna();
}
    
    
    
    
    public void tagokamuna(){
        jbtn_RTdelete.setVisible(false);
        jbtn_Ratedelete.setVisible(false);
         jbtn_Beddelete.setVisible(false);
    }
    
    public void labaskana(){
        jbtn_RTdelete.setVisible(true);
         jbtn_Ratedelete.setVisible(true);
          jbtn_Beddelete.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_ratestable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtble_bedtable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_RTtable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_ro_search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_BedQuantity = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jtxt_BedID = new javax.swing.JTextField();
        jbtn_Beddelete = new javax.swing.JButton();
        jbtn_Bedsave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxt_RateID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxt_RatePrice = new javax.swing.JTextField();
        jbtn_Ratesave = new javax.swing.JButton();
        jbtn_Ratedelete = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxt_RTid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxt_RoomType = new javax.swing.JTextField();
        jbtn_RTsave = new javax.swing.JButton();
        jbtn_RTdelete = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(213, 221, 221));
        setPreferredSize(new java.awt.Dimension(1480, 790));

        jtbl_ratestable.setBackground(new java.awt.Color(191, 191, 191));
        jtbl_ratestable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jtbl_ratestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rate ID", "Rate Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_ratestable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_ratestableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_ratestable);

        jtble_bedtable.setBackground(new java.awt.Color(191, 191, 191));
        jtble_bedtable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jtble_bedtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bed ID", "Bed Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtble_bedtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtble_bedtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtble_bedtable);

        jtbl_RTtable.setBackground(new java.awt.Color(191, 191, 191));
        jtbl_RTtable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jtbl_RTtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RT ID", "Room Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_RTtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_RTtableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtbl_RTtable);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROOMTYPES-RATES-BEDS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 778, -1));
        jPanel1.add(jtxt_ro_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 30));

        jPanel2.setBackground(new java.awt.Color(0, 77, 77));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(191, 191, 191));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BED ACTION");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bed ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 41));

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bed Quantity");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 41));

        jtxt_BedQuantity.setBackground(new java.awt.Color(0, 77, 77));
        jtxt_BedQuantity.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_BedQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_BedQuantity.setBorder(null);
        jtxt_BedQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_BedQuantityKeyTyped(evt);
            }
        });
        jPanel2.add(jtxt_BedQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, 20));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 170, 10));

        jtxt_BedID.setBackground(new java.awt.Color(0, 77, 77));
        jtxt_BedID.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_BedID.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_BedID.setBorder(null);
        jtxt_BedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_BedIDActionPerformed(evt);
            }
        });
        jtxt_BedID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_BedIDKeyTyped(evt);
            }
        });
        jPanel2.add(jtxt_BedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, 20));

        jbtn_Beddelete.setBackground(new java.awt.Color(51, 102, 255));
        jbtn_Beddelete.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_Beddelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Beddelete.setText("DELETE");
        jbtn_Beddelete.setPreferredSize(new java.awt.Dimension(63, 23));
        jbtn_Beddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_BeddeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_Beddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));

        jbtn_Bedsave.setBackground(new java.awt.Color(51, 102, 255));
        jbtn_Bedsave.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_Bedsave.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Bedsave.setText("SAVE");
        jbtn_Bedsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_BedsaveActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_Bedsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));

        jPanel3.setBackground(new java.awt.Color(0, 77, 77));
        jPanel3.setPreferredSize(new java.awt.Dimension(310, 212));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(191, 191, 191));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RATE ACTION");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 50));

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rate ID");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 73, 20));

        jtxt_RateID.setBackground(new java.awt.Color(0, 77, 77));
        jtxt_RateID.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_RateID.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_RateID.setBorder(null);
        jtxt_RateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_RateIDActionPerformed(evt);
            }
        });
        jtxt_RateID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_RateIDKeyTyped(evt);
            }
        });
        jPanel3.add(jtxt_RateID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 190, 20));

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room Price");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 41));

        jtxt_RatePrice.setBackground(new java.awt.Color(0, 77, 77));
        jtxt_RatePrice.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_RatePrice.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_RatePrice.setBorder(null);
        jtxt_RatePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_RatePriceKeyTyped(evt);
            }
        });
        jPanel3.add(jtxt_RatePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, 20));

        jbtn_Ratesave.setBackground(new java.awt.Color(51, 102, 255));
        jbtn_Ratesave.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_Ratesave.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Ratesave.setText("SAVE");
        jbtn_Ratesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RatesaveActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn_Ratesave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));

        jbtn_Ratedelete.setBackground(new java.awt.Color(51, 102, 255));
        jbtn_Ratedelete.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_Ratedelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Ratedelete.setText("DELETE");
        jbtn_Ratedelete.setPreferredSize(new java.awt.Dimension(63, 23));
        jbtn_Ratedelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RatedeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn_Ratedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 190, 10));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, 10));

        jPanel4.setBackground(new java.awt.Color(0, 77, 77));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(191, 191, 191));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ROOMTYPE ACTION");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 54));

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RT ID");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 41));

        jtxt_RTid.setBackground(new java.awt.Color(0, 77, 77));
        jtxt_RTid.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_RTid.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_RTid.setBorder(null);
        jtxt_RTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_RTidActionPerformed(evt);
            }
        });
        jtxt_RTid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_RTidKeyTyped(evt);
            }
        });
        jPanel4.add(jtxt_RTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 62, 200, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Room Type");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 41));

        jtxt_RoomType.setBackground(new java.awt.Color(0, 77, 77));
        jtxt_RoomType.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jtxt_RoomType.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_RoomType.setBorder(null);
        jtxt_RoomType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_RoomTypeKeyTyped(evt);
            }
        });
        jPanel4.add(jtxt_RoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, 20));

        jbtn_RTsave.setBackground(new java.awt.Color(51, 102, 255));
        jbtn_RTsave.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_RTsave.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_RTsave.setText("SAVE");
        jbtn_RTsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RTsaveActionPerformed(evt);
            }
        });
        jPanel4.add(jbtn_RTsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));

        jbtn_RTdelete.setBackground(new java.awt.Color(51, 102, 255));
        jbtn_RTdelete.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_RTdelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_RTdelete.setText("DELETE");
        jbtn_RTdelete.setPreferredSize(new java.awt.Dimension(63, 23));
        jbtn_RTdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RTdeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbtn_RTdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 200, 10));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1499, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbl_ratestableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_ratestableMouseClicked
     try {
            id = (int) jtbl_ratestable.getValueAt(jtbl_ratestable.getSelectedRow(),0);
            ratesControll.fillForm(id, jtxt_RateID, jtxt_RatePrice);
            labaskana();
            jbtn_Ratesave.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jtbl_ratestableMouseClicked

    private void jtble_bedtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtble_bedtableMouseClicked
        // TODO add your handling code here:
        
         try {
            id = (int) jtble_bedtable.getValueAt(jtble_bedtable.getSelectedRow(),0);
            bedsControll.fillForm(id, jtxt_BedID, jtxt_BedQuantity);
            labaskana();
            jbtn_Bedsave.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jtble_bedtableMouseClicked

    private void jtbl_RTtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_RTtableMouseClicked
        // TODO add your handling code here:
        
         try {
            id = (int) jtbl_RTtable.getValueAt(jtbl_RTtable.getSelectedRow(),0);
            roomtypeControll.fillForm(id, jtxt_RTid, jtxt_RoomType);
            labaskana();
            jbtn_RTsave.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jtbl_RTtableMouseClicked

    private void jbtn_BedsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_BedsaveActionPerformed

        
           if (checkInputsBed()==true) {
             JOptionPane.showMessageDialog(this,"ERROR");        
      }else{     
        try {
             
            bedsControll.saveBeds(jtxt_BedID, jtxt_BedQuantity, jtble_bedtable);
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);          
            
        
    }              
           }   
        
    }//GEN-LAST:event_jbtn_BedsaveActionPerformed

    private void jtxt_BedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_BedIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_BedIDActionPerformed

    private void jtxt_RateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_RateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_RateIDActionPerformed

    private void jbtn_RatesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RatesaveActionPerformed
        // TODO add your handling code here:
        
        
           if (checkInputsRate()==true) {
             JOptionPane.showMessageDialog(this,"ERROR");        
      }else{     
        try {
             
            ratesControll.saveRates(jtxt_RateID, jtxt_RatePrice, jtbl_ratestable);
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);          
            
        }
           }   
    }//GEN-LAST:event_jbtn_RatesaveActionPerformed

    private void jtxt_RTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_RTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_RTidActionPerformed

    private void jbtn_RTsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RTsaveActionPerformed
      
         if (checkInputsRT()==true) {
             JOptionPane.showMessageDialog(this,"ERROR");
          
      }else{     
        try { 
            roomtypeControll.saveRT(jtxt_RTid,jtxt_RoomType,jtbl_RTtable);
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);
            
            
            
        }
         }
    }//GEN-LAST:event_jbtn_RTsaveActionPerformed

    private void jbtn_RTdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RTdeleteActionPerformed
        // TODO add your handling code here:
        
          try {
            boolean checkDeleteRoomtypes = roomtypeControll.deleteRoomtypes(id, jtbl_RTtable);
            if (checkDeleteRoomtypes==true) {
                new ContainerManipulator(lalagyanan,new Views.Panels.Rate_RT_BedPanels(lalagyanan));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtn_RTdeleteActionPerformed

    private void jbtn_RatedeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RatedeleteActionPerformed
        // TODO add your handling code here:
        
        
        try {
            boolean checkDeleteRates = ratesControll.deleteRates(id, jtbl_ratestable);
            if (checkDeleteRates==true) {
                new ContainerManipulator(lalagyanan,new Views.Panels.Rate_RT_BedPanels(lalagyanan));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtn_RatedeleteActionPerformed

    private void jbtn_BeddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_BeddeleteActionPerformed
        // TODO add your handling code here:
        
        try {
            boolean checkDeleteBeds = bedsControll.deleteBeds(id, jtble_bedtable);
            if (checkDeleteBeds==true) {
                new ContainerManipulator(lalagyanan,new Views.Panels.Rate_RT_BedPanels(lalagyanan));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rate_RT_BedPanels.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jbtn_BeddeleteActionPerformed

    private void jtxt_RTidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_RTidKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_RTidKeyTyped

    private void jtxt_RateIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_RateIDKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }     
        
    }//GEN-LAST:event_jtxt_RateIDKeyTyped

    private void jtxt_BedIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_BedIDKeyTyped
        // TODO add your handling code here:
        
         char c = evt.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_BedIDKeyTyped

    private void jtxt_RatePriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_RatePriceKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
        
    }//GEN-LAST:event_jtxt_RatePriceKeyTyped

    private void jtxt_RoomTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_RoomTypeKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
         if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'Z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_RoomTypeKeyTyped

    private void jtxt_BedQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_BedQuantityKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
         if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'Z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jtxt_BedQuantityKeyTyped
      
    
     private boolean checkInputsRT(){
        String notice = "Theres Have A Field That Empty Please make an Input";
        if (jtxt_RTid.getText().isEmpty()||jtxt_RoomType.getText().isEmpty()){
         //   JOptionPane.showMessageDialog(this,notice);
            return true;
        }else{
            return false;
        }
      }
     private boolean checkInputsRate(){
        String notice = "Theres Have A Field That Empty Please make an Input";
        if (jtxt_RateID.getText().isEmpty()||jtxt_RatePrice.getText().isEmpty()){
         //   JOptionPane.showMessageDialog(this,notice);
            return true;
        }else{
            return false;
        }
      } 
    private boolean checkInputsBed(){
        String notice = "Theres Have A Field That Empty Please make an Input";
        if (jtxt_BedID.getText().isEmpty()||jtxt_BedQuantity.getText().isEmpty()){
         //   JOptionPane.showMessageDialog(this,notice);
            return true;
        }else{
            return false;
        }
      }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbtn_Beddelete;
    private javax.swing.JButton jbtn_Bedsave;
    private javax.swing.JButton jbtn_RTdelete;
    private javax.swing.JButton jbtn_RTsave;
    private javax.swing.JButton jbtn_Ratedelete;
    private javax.swing.JButton jbtn_Ratesave;
    private javax.swing.JTable jtbl_RTtable;
    private javax.swing.JTable jtbl_ratestable;
    private javax.swing.JTable jtble_bedtable;
    private javax.swing.JTextField jtxt_BedID;
    private javax.swing.JTextField jtxt_BedQuantity;
    private javax.swing.JTextField jtxt_RTid;
    private javax.swing.JTextField jtxt_RateID;
    private javax.swing.JTextField jtxt_RatePrice;
    private javax.swing.JTextField jtxt_RoomType;
    private javax.swing.JTextField jtxt_ro_search;
    // End of variables declaration//GEN-END:variables
}
