/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;
import Controllers.RoomController;
import Models.Rooms;
import Controllers.SQL;
import Views.Dashboards.ContainerManipulator;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chelsea
 * 
 */
public class RoomsPanel extends javax.swing.JPanel {
    
    public RoomController roomControll = new RoomController();
    public ArrayList<Rooms> roomlist = roomControll.roomList();
     public Rooms roomModel;
     public JPanel lalagyanan;
    public int index,index1,id;
    String role;
    
    public RoomsPanel(JPanel lalagyanan,String role) throws SQLException{
        initComponents();
        this.role=role;
        
        if(role.equals("Staff")){
                roomAction.setVisible(false);
                save.setVisible(false);
                roomstable.setVisible(false);
                roomscroll.setVisible(false);
                roomstablestaff.getTableHeader().setFont(new Font("Tw Cen MT", 0, 50));
                roomstablestaff.getTableHeader().setBackground(Color.white);
                roomscrollstaff.setVisible(true);
                roomstablestaff.setVisible(true);
                roomControll.Room(roomstablestaff);
                update.setVisible(false);
        }else{
            roomControll.Room(roomstable);
            if (roomlist.size()==0) {
            Roomid.setText("1");
            InitRun();
        }else{
            index1 = roomlist.size()-1;
            index = roomlist.get(index1).getroom_id() + 1;        
            Roomid.setText(String.valueOf(index));
            InitRun();
        }
        }
        this.lalagyanan=lalagyanan;
    }
    
//    UDF
    private void InitRun(){
        update.setVisible(false);
        roomTypeId.setBackground(new Color(0, 0, 0, 0));
        roomTypeId.setOpaque(false);
        bedTypeId.setBackground(new Color(0, 0, 0, 0));
        bedTypeId.setOpaque(false);
        rateId.setBackground(new Color(0, 0, 0, 0));
        rateId.setOpaque(false);
        statusId.setBackground(new Color(0, 0, 0, 0));
        statusId.setOpaque(false);
        roomControll.showRoomType(roomTypeId);
        roomControll.showBedType(bedTypeId);
        roomControll.showRate(rateId);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        save = new javax.swing.JButton();
        roomAction = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Roomid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        statusId = new javax.swing.JComboBox<>();
        roomTypeId = new javax.swing.JComboBox<>();
        bedTypeId = new javax.swing.JComboBox<>();
        rateId = new javax.swing.JComboBox<>();
        roomscroll = new javax.swing.JScrollPane();
        roomstable = new javax.swing.JTable();
        roomscrollstaff = new javax.swing.JScrollPane();
        roomstablestaff = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 77, 77));
        setPreferredSize(new java.awt.Dimension(1480, 790));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 77, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rooms");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 22, 242, -1));

        update.setBackground(new java.awt.Color(51, 102, 255));
        update.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 126, 61));

        save.setBackground(new java.awt.Color(51, 102, 255));
        save.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 126, 61));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, -1));

        roomAction.setBackground(new java.awt.Color(0, 77, 77));
        roomAction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(191, 191, 191));
        jLabel2.setText("ROOM ACTIONS");
        roomAction.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 54));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room ID");
        roomAction.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 72, 73, 41));

        Roomid.setEditable(false);
        Roomid.setBackground(new java.awt.Color(0, 77, 77));
        Roomid.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        Roomid.setForeground(new java.awt.Color(255, 255, 255));
        Roomid.setBorder(null);
        roomAction.add(Roomid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 213, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Room Type");
        roomAction.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 41));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bed Type");
        roomAction.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 41));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rate");
        roomAction.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 73, 41));

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status");
        roomAction.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 73, 41));
        roomAction.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, -1));
        roomAction.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 210, -1));
        roomAction.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 210, -1));
        roomAction.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 210, -1));
        roomAction.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 210, -1));

        statusId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));
        roomAction.add(statusId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 210, 30));

        roomAction.add(roomTypeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 210, 30));

        roomAction.add(bedTypeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 210, 30));

        roomAction.add(rateId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 210, 30));

        add(roomAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 340, 700));

        roomstable.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        roomstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room Type", "Bed Type", "Rate", "Status"
            }
        ));
        roomstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomstableMouseClicked(evt);
            }
        });
        roomscroll.setViewportView(roomstable);

        add(roomscroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 1140, 690));

        roomscrollstaff.setBackground(new java.awt.Color(0, 77, 77));

        roomstablestaff.setBackground(new java.awt.Color(0, 77, 77));
        roomstablestaff.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        roomstablestaff.setForeground(new java.awt.Color(255, 255, 255));
        roomstablestaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room Type", "Bed Type", "Rate", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roomstablestaff.setEnabled(false);
        roomstablestaff.setGridColor(new java.awt.Color(0, 77, 77));
        roomstablestaff.setRowHeight(40);
        roomstablestaff.setSelectionBackground(new java.awt.Color(0, 77, 77));
        roomstablestaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomstablestaffMouseClicked(evt);
            }
        });
        roomscrollstaff.setViewportView(roomstablestaff);

        add(roomscrollstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1480, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        int roomtype=roomTypeId.getSelectedIndex()+1;
        int bedtype=bedTypeId.getSelectedIndex()+1;
        int rate=rateId.getSelectedIndex()+1;
        int status=statusId.getSelectedIndex();
        if (status==0) {
            roomModel = new Rooms(id,bedtype,roomtype,rate,status+1);  
        }else{
            roomModel = new Rooms(id,bedtype,roomtype,rate,status-1);
        }
        try {
            boolean checkRoom = roomControll.createRooms(roomModel,roomstable);
            if (checkRoom==true) {
//                roomControll.clearContent(Roomid, roomType, Bedtype, Rate, Status);
                new ContainerManipulator(lalagyanan,new Views.Panels.RoomsPanel(lalagyanan,role));
            }
        } catch (SQLException ex) {
            //            Logger.getLogger(roomsomerActions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         int roomtype=roomTypeId.getSelectedIndex()+1;
        int bedtype=bedTypeId.getSelectedIndex()+1;
        int rate=rateId.getSelectedIndex()+1;
        int status=statusId.getSelectedIndex();
        if (status==0) {
            roomModel = new Rooms(id,bedtype,roomtype,rate,status+1);  
        }else{
            roomModel = new Rooms(id,bedtype,roomtype,rate,status-1);
        }
        boolean checkUpdate;
        try {
            checkUpdate = roomControll.updateRooms(roomModel, id, roomstable);
             if (checkUpdate==true) {
                JOptionPane.showMessageDialog(null,"Successfully Updated!!");
//                roomControll.clearContent();
                new ContainerManipulator(lalagyanan,new Views.Panels.RoomsPanel(lalagyanan,role));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void roomstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomstableMouseClicked
        JOptionPane.showMessageDialog(null,"hello");
        update.setVisible(true);
        save.setVisible(false);
        id = (int) roomstable.getValueAt(roomstable.getSelectedRow(),0);
        try {
            roomControll.fillRoomForm(id,Roomid, roomTypeId, bedTypeId, rateId, statusId);
        } catch (SQLException ex) {
            Logger.getLogger(RoomsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_roomstableMouseClicked

    private void roomstablestaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomstablestaffMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roomstablestaffMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Roomid;
    private javax.swing.JComboBox<String> bedTypeId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> rateId;
    private javax.swing.JPanel roomAction;
    private javax.swing.JComboBox<String> roomTypeId;
    private javax.swing.JScrollPane roomscroll;
    private javax.swing.JScrollPane roomscrollstaff;
    private javax.swing.JTable roomstable;
    private javax.swing.JTable roomstablestaff;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> statusId;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
