/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Panels;

import Controllers.BedsController;
import Models.Beds;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Chelsea
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() throws SQLException {
        initComponents();
//        vin.setModel(loadImg());
//   jComboBox1.setSelectedIndex(0);
jComboBox1.setModel(loadImg());
        
//        int i = jComboBox1.getSelectedIndex();
//        jComboBox1.removeItemAt(1);
          
    }
    
    private  DefaultComboBoxModel<Icon> loadImg(){
         DefaultComboBoxModel model = (DefaultComboBoxModel)jComboBox1.getModel();
         
//         model.insertElementAt(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png")),1);
         
           model.addElement("<html><div style='padding:5px;'><img src='src\\Images\\a.jpg'><b>KEVIN FELIX CALUAG</b></html>");
         return model;
    }

    public void showBeds() throws SQLException{
        ArrayList<Beds> list = new BedsController().bedList();
//        Object[] row = new Object[5];
            int A=100;
            int B=120;
            int C=210;
            int D=190;
            
             int E=100;
            int F=360;
            int G=210;
            int H=190;
        JLabel Jlabels []= new JLabel [9];
        JButton but [] = new JButton[9];
        
         for (int i = 0; i < Jlabels.length; i++) {
             if (i>4){
                 Jlabels[i]=new JLabel("jLabel" + i);
                 but[i]=new JButton("Room" + i);
                 but[i].setBackground(Color.green);
                 but[i].setForeground(Color.red);
                 but[i].setFont(new Font("Times New Roman", Font.BOLD, 18));
                Jlabels[i].setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 51)));
            Jlabels[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rooms/r"+i+".gif")));
//                lagyanan.add(Jlabels[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(E,F,G,H));
//                lagyanan.add(but[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(E, 560, G,30));
                E+=250;
             }else{
            Jlabels[i]=new JLabel("jLabel" + i);
            but[i]=new JButton("Room" + i);
            but[i].setBackground(Color.yellow);
            but[i].setForeground(Color.black);
            but[i].setFont(new Font("Times New Roman", Font.BOLD, 18));
            Jlabels[i].setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 51)));
            Jlabels[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rooms/r"+i+".gif")));
//            lagyanan.add(Jlabels[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(A,B,C,D));
//            lagyanan.add(but[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(A, 320, C,30));
            A+=250;
             }
         }
//         
//         lagyanan.validate();
//         lagyanan.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jComboBox1 = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1564, 589));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(jComboBox1.getModel());
        jComboBox1.setSelectedItem(0);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 260, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new test().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Icon> jComboBox1;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
