/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Authentication;

import Controllers.Authentication;
import Controllers.SQL;
import Views.Dashboards.MainDashboard;
import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ❤Kevin Felix Caluag❤
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    Authentication auth = new Authentication();
    PlaceHolder pl;
    JFrame out;
    
    public Login() {
        this.out=this;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxt_username = new javax.swing.JTextField();
        jtxt_password = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jbtn_viewpass = new javax.swing.JButton();
        jbtn_hidepass = new javax.swing.JButton();
        hov3 = new javax.swing.JPanel();
        signin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 75, 102), 5, true));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ornate_hotel_lobby_picture_1_167663.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxt_username.setBackground(new java.awt.Color(0, 204, 255));
        jtxt_username.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jtxt_username.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_username.setBorder(null);
        jtxt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxt_usernameMouseClicked(evt);
            }
        });
        jtxt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 270, 30));

        jtxt_password.setBackground(new java.awt.Color(0, 204, 255));
        jtxt_password.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jtxt_password.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_password.setBorder(null);
        jtxt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxt_passwordMouseClicked(evt);
            }
        });
        jtxt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_passwordActionPerformed(evt);
            }
        });
        jtxt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_passwordKeyPressed(evt);
            }
        });
        jPanel2.add(jtxt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 270, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 270, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 270, 10));

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOG IN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 212, 68));

        jbtn_viewpass.setBackground(new java.awt.Color(0, 204, 255));
        jbtn_viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eyes.png"))); // NOI18N
        jbtn_viewpass.setBorderPainted(false);
        jbtn_viewpass.setContentAreaFilled(false);
        jbtn_viewpass.setFocusPainted(false);
        jbtn_viewpass.setFocusable(false);
        jbtn_viewpass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_viewpass.setMaximumSize(new java.awt.Dimension(55, 49));
        jbtn_viewpass.setMinimumSize(new java.awt.Dimension(55, 49));
        jbtn_viewpass.setPreferredSize(new java.awt.Dimension(60, 49));
        jbtn_viewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_viewpassActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_viewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 30, 30));

        jbtn_hidepass.setBackground(new java.awt.Color(0, 204, 255));
        jbtn_hidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hide.png"))); // NOI18N
        jbtn_hidepass.setBorderPainted(false);
        jbtn_hidepass.setContentAreaFilled(false);
        jbtn_hidepass.setFocusPainted(false);
        jbtn_hidepass.setFocusable(false);
        jbtn_hidepass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_hidepass.setPreferredSize(new java.awt.Dimension(60, 49));
        jbtn_hidepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_hidepassActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_hidepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 30, 30));

        hov3.setBackground(new java.awt.Color(0, 204, 255));

        signin.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin.setText("Sign In");
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hov3Layout = new javax.swing.GroupLayout(hov3);
        hov3.setLayout(hov3Layout);
        hov3Layout.setHorizontalGroup(
            hov3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signin, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        hov3Layout.setVerticalGroup(
            hov3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(hov3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 40));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 5, 380, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void setC(JPanel kev){
         kev.setBackground(new Color(0,153,153));
    }
    
    private void resetC(JPanel kev1){
          kev1.setBackground(new Color(0,204,255));
    }
    private void jtxt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usernameActionPerformed

    private void jbtn_viewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_viewpassActionPerformed
        jtxt_password.setEchoChar((char)0);
        jbtn_hidepass.setVisible(true);
        jbtn_viewpass.setVisible(false);
    }//GEN-LAST:event_jbtn_viewpassActionPerformed

    private void jbtn_hidepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_hidepassActionPerformed
        jbtn_viewpass.setVisible(true);
        jbtn_hidepass.setVisible(false);
        jtxt_password.setEchoChar('*');
    }//GEN-LAST:event_jbtn_hidepassActionPerformed

    private void signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseEntered
         setC(hov3);
    }//GEN-LAST:event_signinMouseEntered

    private void signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseExited
       resetC(hov3);
    }//GEN-LAST:event_signinMouseExited

    private void jtxt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_usernameMouseClicked
        jtxt_username.setText("");
    }//GEN-LAST:event_jtxt_usernameMouseClicked

    private void jtxt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_passwordMouseClicked
        jtxt_password.setText("");
        jtxt_password.setEchoChar('*');
    }//GEN-LAST:event_jtxt_passwordMouseClicked
    
    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
        try {
            auth.signIn(out,jtxt_username,jtxt_password);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signinMouseClicked

    private void jtxt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_passwordKeyPressed
        if(evt.getKeyCode()==10){
            try {
                auth.signIn(out,jtxt_username,jtxt_password);
            } catch (InterruptedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtxt_passwordKeyPressed

    private void jtxt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_passwordActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hov3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jbtn_hidepass;
    private javax.swing.JButton jbtn_viewpass;
    private javax.swing.JPasswordField jtxt_password;
    private javax.swing.JTextField jtxt_username;
    private javax.swing.JLabel signin;
    // End of variables declaration//GEN-END:variables
}