/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Dashboards;

import Views.Authentication.Login;
import Views.Dashboards.ContainerManipulator;
import java.awt.Color;
import java.awt.Component;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ❤Kevin Felix Caluag❤
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     * 
     */
    
    public static String fullname,role;
    
    public AdminDashboard(String fullname,String role) {
        initComponents();
        new ContainerManipulator(lalagyanan,new Views.Panels.Home());
        user_fullname.setText(fullname);
        userrole.setText(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelRound2 = new jroundborder.JLabelRound();
        jLabelRound3 = new jroundborder.JLabelRound();
        jLabelRound1 = new jroundborder.JLabelRound();
        user_fullname = new javax.swing.JLabel();
        userrole = new javax.swing.JLabel();
        hov5 = new javax.swing.JPanel();
        sales = new javax.swing.JLabel();
        hov6 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        hov7 = new javax.swing.JPanel();
        users = new javax.swing.JLabel();
        hov8 = new javax.swing.JPanel();
        rooms = new javax.swing.JLabel();
        hov9 = new javax.swing.JPanel();
        customers = new javax.swing.JLabel();
        lalagyanan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(83, 140, 198));
        jPanel2.setPreferredSize(new java.awt.Dimension(1480, 894));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotelmanagement.gif"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 10, 563, -1));

        jLabelRound2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.gif"))); // NOI18N
        jLabelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRound2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 56, 41, 39));

        jLabelRound3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unlock.gif"))); // NOI18N
        jLabelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRound3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 101, 40, 39));

        jLabelRound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gearmoto.gif"))); // NOI18N
        jLabelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRound1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 11, 40, 39));

        user_fullname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user_fullname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(user_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 11, 310, 39));

        userrole.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        userrole.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(userrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1296, 50, 168, 27));

        hov5.setBackground(new java.awt.Color(83, 140, 198));
        hov5.setPreferredSize(new java.awt.Dimension(230, 40));

        sales.setBackground(new java.awt.Color(51, 51, 255));
        sales.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        sales.setForeground(new java.awt.Color(255, 255, 255));
        sales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.png"))); // NOI18N
        sales.setText("SALES");
        sales.setIconTextGap(10);
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hov5Layout = new javax.swing.GroupLayout(hov5);
        hov5.setLayout(hov5Layout);
        hov5Layout.setHorizontalGroup(
            hov5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sales, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        hov5Layout.setVerticalGroup(
            hov5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(hov5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 150, 50));

        hov6.setBackground(new java.awt.Color(83, 140, 198));
        hov6.setPreferredSize(new java.awt.Dimension(230, 40));

        home.setBackground(new java.awt.Color(51, 51, 255));
        home.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.png"))); // NOI18N
        home.setText("HOME");
        home.setIconTextGap(10);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hov6Layout = new javax.swing.GroupLayout(hov6);
        hov6.setLayout(hov6Layout);
        hov6Layout.setHorizontalGroup(
            hov6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        hov6Layout.setVerticalGroup(
            hov6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(hov6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 150, 50));

        hov7.setBackground(new java.awt.Color(83, 140, 198));
        hov7.setPreferredSize(new java.awt.Dimension(230, 40));

        users.setBackground(new java.awt.Color(51, 51, 255));
        users.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.png"))); // NOI18N
        users.setText("USERS");
        users.setIconTextGap(10);
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hov7Layout = new javax.swing.GroupLayout(hov7);
        hov7.setLayout(hov7Layout);
        hov7Layout.setHorizontalGroup(
            hov7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(users, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        hov7Layout.setVerticalGroup(
            hov7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(hov7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, 50));

        hov8.setBackground(new java.awt.Color(83, 140, 198));
        hov8.setPreferredSize(new java.awt.Dimension(230, 40));

        rooms.setBackground(new java.awt.Color(51, 51, 255));
        rooms.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        rooms.setForeground(new java.awt.Color(255, 255, 255));
        rooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.png"))); // NOI18N
        rooms.setText("ROOMS");
        rooms.setIconTextGap(10);
        rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hov8Layout = new javax.swing.GroupLayout(hov8);
        hov8.setLayout(hov8Layout);
        hov8Layout.setHorizontalGroup(
            hov8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rooms, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        hov8Layout.setVerticalGroup(
            hov8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(hov8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, 50));

        hov9.setBackground(new java.awt.Color(83, 140, 198));
        hov9.setPreferredSize(new java.awt.Dimension(230, 40));

        customers.setBackground(new java.awt.Color(51, 51, 255));
        customers.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        customers.setForeground(new java.awt.Color(255, 255, 255));
        customers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.png"))); // NOI18N
        customers.setText("CUSTOMERS");
        customers.setIconTextGap(10);
        customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hov9Layout = new javax.swing.GroupLayout(hov9);
        hov9.setLayout(hov9Layout);
        hov9Layout.setHorizontalGroup(
            hov9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customers, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        hov9Layout.setVerticalGroup(
            hov9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(hov9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 190, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 150));

        lalagyanan.setPreferredSize(new java.awt.Dimension(1480, 790));
        lalagyanan.setLayout(new javax.swing.BoxLayout(lalagyanan, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(lalagyanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 790));

        jPanel3.setBackground(new java.awt.Color(83, 140, 198));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POWERED BY INNOVATECH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 1480, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRound2MouseClicked
        int result = JOptionPane.showConfirmDialog(this,"Are You Sure That You Want To Sign Out", "LogOut",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (result==0){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabelRound2MouseClicked

    private void jLabelRound3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRound3MouseClicked
        if (sales.isEnabled()) {
            sales.setEnabled(false);
//            checkIn.setEnabled(false);
//            checkOut.setEnabled(false);
//            customers.setEnabled(false);
//            hov1.setEnabled(false);
//            hov2.setEnabled(false);
//            hov3.setEnabled(false);
//            hov4.setEnabled(false);
        }else{
            sales.setEnabled(true);
//            checkIn.setEnabled(true);
//            checkOut.setEnabled(true);
//            customers.setEnabled(true);
//            hov1.setEnabled(true);
//            hov2.setEnabled(true);
//            hov3.setEnabled(true);
//            hov4.setEnabled(true);
        }
    }//GEN-LAST:event_jLabelRound3MouseClicked

    private void jLabelRound1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRound1MouseClicked
        JOptionPane.showConfirmDialog(null, new Views.Panels.Receipts(), "Receipt", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        //            new Views.Panels.Receipts().setVisible(true);
    }//GEN-LAST:event_jLabelRound1MouseClicked

    private void salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseClicked
        if (sales.isEnabled()) {
            try {
                new ContainerManipulator(lalagyanan,new Views.Panels.SalesPanel());
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(StaffAndManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_salesMouseClicked

    private void salesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseEntered
        setC(hov5);
    }//GEN-LAST:event_salesMouseEntered

    private void salesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseExited
        resetC(hov5);
    }//GEN-LAST:event_salesMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        if (sales.isEnabled()) {
            new ContainerManipulator(lalagyanan,new Views.Panels.Home());
        }
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        setC(hov6);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        resetC(hov6);
    }//GEN-LAST:event_homeMouseExited

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        if (users.isEnabled()) {
            try {
                new ContainerManipulator(lalagyanan,new Views.Panels.UsersPanel());
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(StaffAndManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_usersMouseClicked

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
        setC(hov7);
    }//GEN-LAST:event_usersMouseEntered

    private void usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseExited
        resetC(hov7);
    }//GEN-LAST:event_usersMouseExited

    private void roomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseClicked
        // TODO add your handling code here:
        if (rooms.isEnabled()) {
            try {
                new ContainerManipulator(lalagyanan,new Views.Panels.RoomsPanel());
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(StaffAndManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_roomsMouseClicked

    private void roomsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseEntered
        setC(hov8);
    }//GEN-LAST:event_roomsMouseEntered

    private void roomsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseExited
        resetC(hov8);
    }//GEN-LAST:event_roomsMouseExited

    private void customersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersMouseClicked
        // TODO add your handling code here:
        if (customers.isEnabled()) {
            try {
                new ContainerManipulator(lalagyanan,new Views.Panels.CustomersPanel(lalagyanan));
//                new ContainerManipulator(actions,new Views.Panels.CustomerActions());
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_customersMouseClicked

    private void customersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersMouseEntered
        setC(hov9);
    }//GEN-LAST:event_customersMouseEntered

    private void customersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersMouseExited
        resetC(hov9);
    }//GEN-LAST:event_customersMouseExited
    
    private void setC(JPanel kev){
         kev.setBackground(new Color(102, 140, 255));
    }
    
    private void resetC(JPanel kev1){
           kev1.setBackground(new Color(83,140,198));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard(fullname,role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customers;
    private javax.swing.JLabel home;
    private javax.swing.JPanel hov5;
    private javax.swing.JPanel hov6;
    private javax.swing.JPanel hov7;
    private javax.swing.JPanel hov8;
    private javax.swing.JPanel hov9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private jroundborder.JLabelRound jLabelRound1;
    private jroundborder.JLabelRound jLabelRound2;
    private jroundborder.JLabelRound jLabelRound3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lalagyanan;
    private javax.swing.JLabel rooms;
    private javax.swing.JLabel sales;
    private javax.swing.JLabel user_fullname;
    private javax.swing.JLabel userrole;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
