/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Dashboards;

import Controllers.Buttons;
import Controllers.CheckinAndOutController;
import Controllers.SQL;
import Views.Authentication.Login;
import java.awt.Color;
import javax.swing.JPanel;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author ❤Kevin Felix Caluag❤
 */
public class MainDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     * 
     */
    
    public static String fullname,role;
    JFrame MainDashboard;
    static int user_id;
    
    public MainDashboard(int user_id,String fullname,String role) throws SQLException {
        initComponents();
        this.user_id=user_id;
        this.MainDashboard=this;
        new ContainerManipulator(lalagyanan,new Views.Panels.Home());
        this.role=role; 
        this.fullname=fullname;
        checkRole();
//        startTH(true);
        
    }
    
    private void startTH(boolean val){
        while(true){
            Calendar cal = Calendar.getInstance();
            int hour = cal.get(Calendar.HOUR_OF_DAY);
            int minute = cal.get(Calendar.MINUTE);
            int second = cal.get(Calendar.SECOND);
            Date dat = cal.getTime();
            SimpleDateFormat kevs = new SimpleDateFormat("hh:mm:ss aa");
            String times = kevs.format(dat);
            String timess = kevs.format(dat);
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = dateFormat.format(dat);
            date.setText(strDate);
            time.setText(times);
//            checkCustomerCheckOut(timess);
        }
    }
    
    

    
    private void checkRole() throws SQLException{
        if (role.equals("Administrator")){
            new ContainerManipulator(UserButtonsLalagyanan,new Views.Dashboards.AdminButtons(user_id,MainDashboard,fullname, role, lalagyanan));
        }else if(role.equals("Staff")){
            new ContainerManipulator(UserButtonsLalagyanan,new Views.Dashboards.StaffButtons(user_id,MainDashboard,fullname, role, lalagyanan));
        }else{
            new ContainerManipulator(UserButtonsLalagyanan,new Views.Dashboards.ManagerButtons(user_id,MainDashboard,fullname, role, lalagyanan));
        }
    }
    
    public  SQL sql = new SQL();
    public Connection con = sql.getConnection();
    
    String kk;
    
    public String getTimeNow(){
         Calendar date = Calendar.getInstance();  
        SimpleDateFormat kev = new SimpleDateFormat("hh:mm"); 
        SimpleDateFormat kevs = new SimpleDateFormat("hh:mm aa");
//        date.add(Calendar.MINUTE,+1);
        java.util.Date strTime = date.getTime();
        kk = kev.format(strTime);
//        String kkk = kevs.format(strTime);
//        orayt.setText(kkk);
        return kk;
     }
    
    public void checkCustomerCheckOut(String timess) throws SQLException, InterruptedException{
            String checkOutCheck = "SELECT * FROM `checkinandout` LEFT JOIN customers ON customers.cust_id=checkinandout.cust_id LEFT JOIN rooms ON rooms.room_id=checkinandout.room_id";
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery(checkOutCheck);
                        
                        while(rs.next()){
                            String checkouttime = rs.getString("timeout");
//                            JOptionPane.showMessageDialog(null,timess);
                            if (timess.equals(checkouttime)) {
//                                JOptionPane.showMessageDialog(null,checkouttime);
//                                JOptionPane.showMessageDialog(null,timess);
                                JOptionPane.showMessageDialog(null,"Customer @ room " + " " + rs.getInt("room_id") + " " + "is time out");
//                                new VideoFeeder().sleep(5000);
                            }
                        }
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lalagyanan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserButtonsLalagyanan = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainDashboard");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lalagyanan.setPreferredSize(new java.awt.Dimension(1480, 790));
        lalagyanan.setLayout(new javax.swing.BoxLayout(lalagyanan, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(lalagyanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 800));

        jPanel3.setBackground(new java.awt.Color(83, 140, 198));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POWERED BY INNOVATECH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 1480, 50));

        UserButtonsLalagyanan.setLayout(new javax.swing.BoxLayout(UserButtonsLalagyanan, javax.swing.BoxLayout.LINE_AXIS));

        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserButtonsLalagyanan.add(time);

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserButtonsLalagyanan.add(date);

        getContentPane().add(UserButtonsLalagyanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
            private void setC(JPanel kev){
         kev.setBackground(new Color(102, 140, 255));
    }
    
    private void resetC(JPanel kev1){
           kev1.setBackground(new Color(83,140,198));
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainDashboard(user_id,fullname,role).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserButtonsLalagyanan;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lalagyanan;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
